repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: Cargo fmt
        entry: cargo fmt --
        language: system
        types: [rust]
        pass_filenames: false
      
      - id: cargo-check
        name: Cargo check
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false
      
      - id: cargo-clippy
        name: Cargo clippy
        entry: cargo clippy -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
      
      - id: cargo-test
        name: Cargo test
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false